services:
  - type: web
    name: computer-vision-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    runtime: python3
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.12
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/images
